default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: wayfinder_development

test:
  <<: *default
  database: wayfinder_test

production:
  <<: *default
  database: wayfinder_production
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
