default: &default
  adapter: postgresql
  encoding: unicode
  username: logan
  password:
  host: localhost

development:
  <<: *default
  database: ton_app_development

test:
  <<: *default
  database: ton_app_test
